run:
  skip-dirs:
    - vendor/
output:
  option: value
linters:
  disable-all: true
  enable:
    - goimports
linters-settings:
  goimports:
    local-prefixes: github.com/snapp-cab/ceph-s3-operator
