apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindConfig: "./kind-config.yaml"
crdDir: "./config/crd/bases"
testDirs:
- "./testing/"
timeout: 240
# Load the necessary container images as cache
kindContainers:
- s3-operator
