apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-s3-operator.fullname" . }}-clusterresourcequota-updater
  labels:
  {{- include "ceph-s3-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas/status
  verbs:
  - update
  - patch