apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-s3-operator.fullname" . }}-clusterresourcequota-updater-binding
  labels:
  {{- include "ceph-s3-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "ceph-s3-operator.fullname" . }}-clusterresourcequota-updater'
subjects:
- kind: ServiceAccount
  name: '{{ include "ceph-s3-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'