apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-s3-operator.fullname" . }}-manager-role
  labels:
  {{- include "ceph-s3-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3buckets/finalizers
  verbs:
  - update
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3userclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3userclaims/finalizers
  verbs:
  - update
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3userclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3users/finalizers
  verbs:
  - update
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3users/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-s3-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ceph-s3-operator
    app.kubernetes.io/part-of: ceph-s3-operator
  {{- include "ceph-s3-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "ceph-s3-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "ceph-s3-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'