# These access controles are needed for updating resouce quota of the namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcequota-status-updater
rules:
- apiGroups: [""]
  resources: ["resourcequotas/status"]
  verbs: ["update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resourcequota-status-updater-binding
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
roleRef:
  kind: ClusterRole
  name: resourcequota-status-updater
  apiGroup: rbac.authorization.k8s.io

