# permissions for end users to view s3users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: s3user-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ceph-s3-operator
    app.kubernetes.io/part-of: ceph-s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3user-viewer-role
rules:
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3.snappcloud.io
  resources:
  - s3users/status
  verbs:
  - get
