s3UserClass: ceph-default
clusterName: okd4-main
validationWebhookTimeoutSeconds: 10
rgw:
  endpoint: http://localhost:8000
  accessKey: 2262XNX11FZRR44XWIRD
  secretKey: rmtuS1Uj1bIC08QFYGW18GfSHAbkPqdsuYynNudw
