apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Storage
    description: 'Provision and manage S3 users and buckets in S3 object storage created with Ceph RGW on Kubernetes and OpenShift.'
    repository: https://github.com/snapp-incubator/ceph-s3-operator
    support: Snappcloud
  name: ceph-s3-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: S3 Bucket Instance
      displayName: S3 Bucket
      kind: S3Bucket
      name: s3buckets.s3.snappcloud.io
      version: v1alpha1
    - description: S3 User Claim Instance
      displayName: S3 User Claim
      kind: S3UserClaim
      name: s3userclaims.s3.snappcloud.io
      version: v1alpha1
    - description: S3 User is created by the S3 User Claim instance. It's applicable
        for the the operator user.
      displayName: S3 User
      kind: S3User
      name: s3users.s3.snappcloud.io
      version: v1alpha1
  description: |
    The Ceph S3 Operator, an open-source endeavor, is crafted to streamline the management of S3 users and buckets within a Ceph cluster environment. It enhances efficiency and simplifies processes, rendering S3 usage on Ceph clusters more straightforward and user-friendly.

    ## Features

    - S3 User Management
    - Bucket Management
    - Subuser Support
    - Bucket policy Support
    - Quota Management
    - Webhook Integration
    - E2E Testing
    - Helm Chart and OLM Support

    ## Usage and Documentation

    - CRD Examples: Located in the [samples](config/samples) folder.
    - Detailed Documentation: Available on the [wiki](https://github.com/snapp-incubator/ceph-s3-operator/wiki).
    - Design and Decision Insights: Refer to our [design doc](docs/DESIGN.md) for an in-depth understanding.
  displayName: Ceph S3 Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAABFFBMVEVHcEwBGUDs/v8JEzPw//8ABysAFDzs///u//8ABCgHIEYOGzoYO1MaIT8gRlkRMk4uZHE/RF0wN1LQ4+dk18dOp6MAACIpXGzR/PpImplXwrjd8PLH2+EvRWMQKkpj0cIQJ0IFDi83dX0ZLE/V6Ozk9/gdMlYJKElBjI9le5BezL89TWofTGFKY3lXboSSprW2ydM2eoNQraeds78iU2U7gIVRV23Bw8sjOFtWtq+Knq91iZxCk5Qwbnl+l6PGy9KJjJvp/P1BV3Qza3Svsbt8f5ChpbBtcIKTmKaAhpRhZXi7vcVPwLmwu8N6kaFIoZ/Y/fuovMd2eIlppajH8PBcu7K85+OQ2dKJ29Ruwb2e1NKaxMYjpOsOAAAAAXRSTlMAQObYZgAAAxhJREFUSMfV1seS20YQBmCCQA+nkQESwIIBAHPOOedMbpRkS37/9/DBrpIPW14R3IPdp8HlqxlUV/cfCAQCgUDo1goGg8Gfx79PgZ/lB/zHxyeA79ZngUE/IKWUftoNKReMhePxTDbE0U8A6TI+qiVy6fSgXGxnQvRusFFLMzxRrA7D88xgHKZ3gTQ2ThOxMBEnVkq1WimFDOrZO0AaXxFZlL+uZbdr2YoR6Qp5phijfkEaTxC1ZLMCOIa67gIreqlhhVQz1B9IM2Wm6doeoKTLqXVaQgT5a8kitew7TfgL4LJIppECi6Bf47VEuT7XkgBOq9RhRr5A+sJXSjaL2As/Pzx8+fLwHDsCgDOMKrk49fHkbJU3oh4CFp8f/qrndhIAZbdAisHbQdrgrYiKACAVZ7PZ42w2e9QRAZKFkph7tx0/AMfMU1RA0A8HDVHSdMD0YtcDQNFtMnXuZjC7ykcLgNL5uJ9r2vzbj5p0XuznGgLbMpji7U/ODIisAGp91jydrr9dLpfqFszFCQFEkayyt4JcPK2kBECpv2dR+G5Pp5eOCazEAoCT4hOxW0EaT1daHgCUz9eiPCldLpdKdXdeCAgotxQfYDhHPBZQ30q9mtw0oq0nudrTNlsEEDxSvhkMxRJ5Y42o9VkTqm+VaHf9JpnmfgeQLEyY6vJmMFjjhy0WhM3uuLnqid/fhHH/sJj3ELySzTze3odcnWm6MoK0P54ks/ZHWwDtdasBoBqx+IaPxg4PxJKdBDT1k4mH41U3pdckAgjDYf7dX/jhtBmTZkQFwHJf7831xU5/3bAAyW5EZep+hgMXTvCG2wFgt/1zD6VDf6MhgBqZMKuYvwH74ihDV00CCKyiWoLAIrBT9ymfa1CfO2XEK0Zk4iF6tjVNAUKyELHzTpv6XVLLkcM3o7Ioym63YwhWQUk1mXQ7eMdefkkQR7CfRENVuxU32iGk3Lhr0dPMOEecCl9JTR2xk2cGjxl6X3KgofBoleMJQxg+Vx2F748iIUqz4Ua7Xm83Mst/j2C/Huco5TiO+zDQ/WcT7P8N/BPhp5ZUR1rpKAAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - s3
  - ceph
  links:
  - name: Documentation
    url: https://github.com/snapp-incubator/ceph-s3-operator/wiki
  maintainers:
  - email: hamed.karbasi@snapp.cab
    name: Hamed Karbasi
  maturity: stable
  minKubeVersion: 1.21.0
  provider:
    name: Snappcloud
    url: https://github.com/snapp-incubator
  version: 0.0.0
