apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: s3-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: S3Bucket is the Schema for the s3buckets API
      displayName: S3 Bucket
      kind: S3Bucket
      name: s3buckets.s3.snappcloud.io
      version: v1alpha1
    - displayName: S3 User Claim
      kind: S3UserClaim
      name: s3userclaims.s3.snappcloud.io
      version: v1alpha1
    - displayName: S3 User
      kind: S3User
      name: s3users.s3.snappcloud.io
      version: v1alpha1
  description: an operator to handle s3 object storage
  displayName: s3-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - s3
  links:
  - name: S3 Operator
    url: https://s3-operator.domain
  maturity: alpha
  provider:
    name: SanppCloud
  version: 0.0.0
