apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# bases:
# - environment-variables/

configMapGenerator:
- name: environment-variables
  envs: [environment-properties.env]
  behavior: create

vars:
- name: CA_BUNDLE
  objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.CA_BUNDLE

configurations:
  - env-var-transformer.yaml

resources:
  - ../webhook/

namespace: kube-system

patchesJson6902:
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    path: webhook-clientconfig-patch.yaml
