apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../webhook/

namespace: kube-system

patchesJson6902:
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    path: webhook-clientconfig-patch.yaml
