apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: s3bucket
    app.kubernetes.io/instance: s3bucket-sample
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: s3bucket-sample
spec:
  s3ClassName: ceph-rbd
  s3UserName: myuser
