apiVersion: s3.snappcloud.io/v1alpha1
kind: S3UserClaim
metadata:
  labels:
    app.kubernetes.io/name: s3userclaim
    app.kubernetes.io/instance: s3userclaim-sample
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: s3userclaim-sample
spec:
  # TODO(user): Add fields here
