apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "s3-operator.fullname" . }}-resourcequota-status-updater
  labels:
  {{- include "s3-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - resourcequotas/status
  verbs:
  - update
  - patch