apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "s3-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "s3-operator.fullname" . }}-serving-cert
  labels:
  {{- include "s3-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "s3-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-s3-snappcloud-io-v1alpha1-s3bucket
  failurePolicy: Fail
  name: vs3bucket.kb.io
  rules:
  - apiGroups:
    - s3.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - s3buckets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "s3-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-s3-snappcloud-io-v1alpha1-s3userclaim
  failurePolicy: Fail
  name: vs3userclaim.kb.io
  rules:
  - apiGroups:
    - s3.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - s3userclaims
  sideEffects: None