apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-cluster
  namespace: ceph-s3-operator-system
status:
  readyReplicas: 1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-s3-operator-controller-manager
  namespace: ceph-s3-operator-system
status:
  readyReplicas: 1