apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-sample-delete
  namespace: s3-test
spec:
  s3UserRef: s3userclaim-sample
  s3DeletionPolicy: delete

---

apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-sample-retain
  namespace: s3-test
spec:
  s3UserRef: s3userclaim-sample
  s3DeletionPolicy: retain

---
# Create bucket for extra user

apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-extra-delete
  namespace: s3-test
spec:
  s3UserRef: s3userclaim-extra
  s3DeletionPolicy: delete