apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-sample-delete
  namespace: s3-test
spec:
  s3UserRef: s3userclaim-sample
  s3DeletionPolicy: delete

---

apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-sample-retain
  namespace: s3-test
spec:
  s3UserRef: s3userclaim-sample
  s3DeletionPolicy: retain

---
# Create bucket for extra user

apiVersion: s3.snappcloud.io/v1alpha1
kind: S3Bucket
metadata:
  name: s3bucket-extra-delete
  namespace: s3-test2
spec:
  s3UserRef: s3userclaim-extra
  s3DeletionPolicy: delete

---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # Forward the ceph-cluster port on the host
  - command: kubectl port-forward -n s3-operator-system deployment/ceph-cluster 8000:80
    background: true 
    skipLogOutput: true