apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: kubectl apply -f misc/bucket-sample-updated.yaml
    ignoreFailure: true
  - command: kubectl apply -f misc/s3bucket-wrong-s3userref.yaml
    ignoreFailure: true
assert:
  - misc/s3bucket-ok.yaml
error:
  - misc/s3bucket-wrong-s3userref.yaml
