---

apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 30
commands:
  # Check if the buckets are existed on s3
- script: aws --endpoint-url "http://127.0.0.1:8000" s3api list-buckets --profile ceph-test | grep s3bucket-sample-delete | [ $(wc -c) -eq 0 ]
- script: aws --endpoint-url "http://127.0.0.1:8000" s3api list-buckets --profile ceph-test | grep s3bucket-sample-retain 