# Assert creating the secret
apiVersion: v1
kind: Secret
metadata:
  name: s3userclaim-sample-subuser1
  namespace: s3-test
type: Opaque

---
# Assert that this user would see the buckets
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 5
commands:
- command: testing/e2e/set-aws-secret.sh ceph-subuser1 s3userclaim-sample-subuser1
