apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: ./set-aws-secret.sh ceph-subuser1 s3userclaim-sample-subuser1
  - command: ./set-aws-secret.sh ceph-subuser2 s3userclaim-sample-subuser2
  - command: kubectl apply -f bucket-with-subuser-access.yaml
