# Assert that this user would see the buckets
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 5
commands:
  # Subuser must now be able to get an object
- script: aws s3 --endpoint-url "http://127.0.0.1:8000" ls s3://s3bucket-sample-delete --profile ceph-subuser1 | grep "test-object.txt"
 