# Creating s3userclaim with existing secrets must be deined
apiVersion: s3.snappcloud.io/v1alpha1
kind: S3UserClaim
metadata:
  name: s3userclaim-sample2
  namespace: s3-test
spec:
  s3UserClass: ceph-default
  # existing secrets
  readonlySecret: s3-sample-readonly-secret
  adminSecret: s3-sample-admin-secret
  quota:
    maxSize: 100
    maxObjects: 50
    maxBuckets: 5

